---
title: "CV"
output: html_document
---

```{=html}
<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>
```
<div class="row" style="padding-top: 30px;">

# Coming soon!

test

**Dr. Nicholas J. Bishop**

Curriculum Vitae

Assistant Professor

Human Development and Family Sciences

School of Family and Consumer Science

Texas State University Drive

601 University Drive

San Marcos, TX 78666

<a href="mailto:nicholas.bishop@txstate.edu" style="font-size:16px;"> E-mail:nicholas.bishop\@txstate.edu</a>

[**ACADEMIC/PROFESSIONAL BACKGROUND**]{.underline}

**Education**

**University Experience**

**Relevant Professional Experience**

[**GRANTS AND CONTRACTS**]{.underline}

**Funded External Grants and Contracts (2; Total external funding received: \$99,416)**

1\. **Bishop, N. J.** (PI), & Zuniga, K. E. (Co-PI) Investigating Walnut Consumption, Age, and Changes in Cognitive Health in a Nationally-Representative Sample of Older U.S. Adults. Funder: California Walnut Commission, \$64,751. (Submitted: July 10, 2018, Funded: September 1, 2018 -- June 30, 2019).

2.  **Bishop, N. J.** (PI), & Zuniga, K.E. (Co-PI). Investigating Egg Consumption, Choline and Lutein Intake, Age, and Changes in Cognitive Health in a Nationally Representative Sample of Older Adults. Funder: Egg Nutrition Center, \$34,665. (Submitted: May 1, 2017, Funded: February 1, 2018 - August 31, 2018).

**Funded Internal Grants and Contracts (3; Total internal funding received: \$28, 500)**

1.     **Bishop, N. J.** (PI). Food Insecurity, Dietary Quality, and Chronic Disease Progression
in a Representative Sample of Older U.S. Adults: Do Federal and Local Nutrition Assistance Programs Play a Protective Role? Funder: Texas State University, Research Enhancement Program, \$8,000. (Submitted: October 8, 2019, Funded: January 22, 2020 -- May 20, 2021).

2.     **Bishop, N. J.** (PI), & Zuniga, K. E. (Co-PI). Empirically Derived Dietary Patterns
and Cognitive Decline in Older Adults: An Application of Exploratory Factor Mixture Models. Funder: Texas State University, Texas State University, \$15,550. (Submitted: October
6, 2016, Funded: January 7, 2017 -- May 31, 2017).

3.     Goble, P. M. (PI), Yishan Shen (Co-PI), Perez-Brena, N. J. (Co-PI), Weimer, A.
(Co-PI), & **Bishop, N. J.** (Co-I). Opportunities for Undergraduate Research in Human Development & Family Science (OUR HDFS) Fellowship. Funder: Texas State University, College of Applied Arts, \$5,000. (Submitted June 11, 2021, Funded August 5, 2021 -- July 31,
2022).

**External Grant Applications Not Funded (6)**

1.    **Bishop, N. J.** (PI), Quiñones, A. R. (Co-I), & Haas, S. A. (Co-I). Concurrent Progression of Multimorbidity and Cognitive Impairment among Older Adults. PAR-20-179: Advancing Research to Develop Improved Measures and Methods for Understanding Multimorbidity. Funder: National Institutes of Health, Office of Disease Prevention, \$1,624,388.68 (Submitted October 4, 2021).

2.    Goble, P. M., Shen, Y., Perez-Brena, N. J., Weimer, A. A., Alfaro, E. C., **Bishop, N. J.** REU Site: Opportunities for Undergraduate Research in Human Development and Family Sciences (OUR HDFS) Fellowship Program, Federal, \$369,778.00. (Submitted August 23, 2021).

3.    **Bishop, N. J.** (PI), Quiñones, A. R. (Co-I), & Haas, S. A. (Co-I). Concurrent Progression of Multimorbidity and Cognitive Impairment among Older Adults. PAR-20-179: Advancing Research to Develop Improved Measures and Methods for Understanding Multimorbidity. Funder: National Institutes of Health, Office of Disease Prevention, \$1,504,891. (Submitted February 1, 2021).

4.     **Bishop, N. J.** (PI), & Zuniga, K. E. (Co-PI). Investigating Peanut Intake, Progression in Physical Disablement, and Mortality in a Representative Sample of Older U.S. Adults. Funder: The Peanut Institute. \$112,133. (Submitted March 24, 2020).

5.     **Bishop, N. J.** (PI), & Zuniga, K. E. (Co-PI). Food Insecurity, Dietary Quality,
and Chronic Disease Progression in a Representative Sample of Older U.S. Adults: Do Federal and Local Nutrition Assistance Programs Play a Protective Role? Funder: University of Kentucky Center for Poverty Research/United States Department of Agriculture, \$249,819. (Submitted January 18, 2019).

6.     Smith, K. (PI), **Bishop, N.** (co-PI), Gray, G. (co-PI), Tamir, D. (co-PI), & Williams, R.
(co-PI). SoberCat Smartphone App to Decrease Binge Drinking in College Students. Funder: National Institutes of Health, National Institute on Alcohol Abuse and Alcoholism, \$398,412. (Submitted March 16, 2016).

[**RESEARCH (\*designates student author)**]{.underline}

**Refereed Journal Articles (21)**

1.     Pan, X., Luo, Y., & **Bishop, N.** Cognitive function among non-custodial grandparents: Across- national perspective. *The International Journal of Aging and Human Development* (Accepted September 12, 2021; **Impact factor, 2021: 2.224**).

2.     Tucker, J.\*, **Bishop, N. J.**, Wang, K., & Phillips, F. Marital transitions, change in
depression, and quality of social relationships in aging U.S. adults: An analysis of the Health and Retirement Study. *The International Journal of Aging and Human Development*
<https://doi.org/10.1177/00914150211066551> (**Impact factor, 2021: 2.224**).

3.    **Bishop, N. J.**, Ullevig, S., Wang, K., & Zuniga, K. E. Dietary quality modifies the association between multimorbidity and change in mobility limitations among older Americans. *Preventive Medicine*, *153*, 106721. <https://doi.org/10.1016/j.ypmed.2021.106721> (**Impact factor, 2021: 4.018**)

4.    **Bishop, N. J.**, & Zuniga, K. E. (2021). Investigating walnut consumption and cognitive
trajectories in a representative sample of older U.S. adults. *Public Health Nutrition, 24*(7), 1741-1752. [https://doi.org/10.1017/S1368980020001287 ](https://doi.org/10.1017/S1368980020001287)(**Impact factor, 2019: 3.182**)

5.     Zuniga, K. E., **Bishop, N. J.**, & Turner, A. S.\* (2021). Dietary lutein and zeaxanthin are associated with working memory in an older adult population. *Public Health Nutrition*,
*24*(7), 1708-1715. [https://doi.org/10.1017/S1368980019005020 ](https://doi.org/10.1017/S1368980019005020)(**Impact factor, 2019: 3.182**)

6.     Wang, K., Gao, X., Sun, F., & **Bishop, N.** (2020). Health literacy and caregiver burden among Chinese caregivers of older adults with cognitive impairment: Does education matter? *Journal of Applied Gerontology*. <https://doi.org/10.1177%2F0733464820957151> **(Impact factor, 2019: 2.144)**

7.     Hegde, A. L., & **Bishop, N. J.** (2020). Simulation and reflective experience: An effective teaching strategy to sensitize interior design students to the visual needs of older adults and the visually impaired. *Design & Communication in Higher Education*, *19*(1), 33-49. <https://doi.org/10.1386/adch_00012_1> (**Impact factor, 2018: 0.41**)

8.     Wang, K., Xie, Y., Wang, D., **Bishop, N. J.**, Tooker, E.\*, & Li, Z. (2020). Socioeconomic correlates of adherence to mineral intake recommendations among pregnant women in north China: Findings from a cohort in Hebei Province. *Asia Pacific Journal of Clinical Nutrition*, *29*(1), 127-135. <https://pubmed.ncbi.nlm.nih.gov/32229451/> (**Impact factor: NA**)

9.     Wang, K., & **Bishop, N. J.** (2019). Social support and monetary resources as protective factors against food insecurity among older Americans: Findings from the Health and Retirement Study. *Food Security, 11*(4), 929-939. <https://doi.org/10.1007/s12571-019-00945-8> (**Impact factor, 2019: 2.095**)

10.     **Bishop, N. J.**, Zuniga, K. E., & Ramirez, C. M.\* (2019). Latent profile analysis of dietary intake in a representative sample of older Americans. *Public Health Nutrition, 23*(2), 243-253. <https://doi.org/10.1017/S1368980019001496> (**Impact factor, 2019: 3.182**)

11.     **Bishop, N. J.**, & Zuniga, K. E. (2019). Egg consumption, multi-domain cognitive performance, and short-term cognitive change in a representative sample of older U.S. Adults. *Journal of the American College of Nutrition*, *38*(6)*,* 537-546. <https://doi.org/10.1080/07315724.2019.1566035> (**Impact factor, 2019: 2.297**)

12.     **Bishop, N. J.**, & Wang, K. (2018). Food insecurity, comorbidity, and mobility limitations among older U.S. adults: Findings from the Health and Retirement Study and Health Care and Nutrition Study. *Preventive Medicine, 114*, 180-187. <https://doi.org/10.1016/j.ypmed.2018.07.001> (**Impact factor, 2018: 3.449**)

13.     Zuniga, K., & **Bishop, N. J.** (2018). Recent cancer treatment and memory decline in older adults: An analysis of the 2002-2012 Health and Retirement Study. *Journal of Geriatric Oncology*, *9*(3), 186-193. <https://doi.org/10.1016/j.jgo.2017.10.004> (**Impact factor, 2018: 3.164**)

14.     Crixell, S. L., Markides, B. R.\*, Biediger-Friedman, L. M., **Bishop, N. J.**, & Reat, A.
M.\* (2018). Designing a WIC app to improve health behaviors: A latent class analysis. *Journal of Mobile Technology in Medicine*, *7*(3), 7-16. <http://dx.doi.org/10.7309/jmtm.7.2.2> (**Impact factor: NA**)

15.     Hegde, A. L., & **Bishop, N. J.** (2018). Saturation based color appearance of objects: A comparison between healthy elderly, young adults, and young adults wearing goggles simulating cataract. *Building and Environment*, *127*, 148-156. [https://doi.org/10.1016/j.buildenv.2017.11.007 ](https://doi.org/10.1016/j.buildenv.2017.11.007)(**Impact factor, 2018: 4.820**)

16.     **Bishop, N. J.**, Zuniga, K. E., & Lucht, A.\* (2018). Latent profiles of macronutrient density and their association with mobility limitations in an observational longitudinal study of older U.S. adults. *The Journal of Nutrition, Health, & Aging*, *22*(6), 645-654. [https://doi.org/10.1007/s12603-017-0986-0 ](https://doi.org/10.1007/s12603-017-0986-0)(**Impact factor, 2018: 2.660**)

17.     **Bishop, N. J.**, Eggum-Wilkens, N. D., Haas, S. A., & Kronenfeld, J. J. (2016). Estimating the co-development of cognitive decline and physical mobility limitations in older U.S. adults. *Demography*, *53*(2), 337-364. <https://doi.org/10.1007/s13524-016-0458-x> (**Impact factor, 2016: 2.802**)

18.     Schaefer, D. R., Haas, S. A., & **Bishop, N. J.** (2012). A dynamic model of U.S. adolescents' smoking and friendship networks. *American Journal of Public Health*, *102*(6), e12-e18. [https://]{.underline} [doi.org/10.2105/AJPH.2012.300705 (**Impact**](https://doi.org/10.2105/AJPH.2012.300705) **factor, 2012: 3.930**)

19.     **Bishop, N. J.** (2011). Predicting rapid DUI recidivism using the Driver Risk Inventory on a state-wide sample of Floridian DUI offenders. *Drug and Alcohol Dependence*, *118*(2), 423-429. [https://doi.org/10.1016/j.drugalcdep.2011.05.006 ](https://doi.org/10.1016/j.drugalcdep.2011.05.006)(**Impact factor, 2011: 3.383**)

20.     **Bishop, N. J.** (2011). Predicting multiple DUI offenders using the Florida DRI. *Substance Use & Misuse*, *46*(5), 696-703. <https://doi.org/10.3109/10826084.2010.529629> (**Impact factor, 2011: 1.104**)

21.     Haas, S. A., & **Bishop, N. J.** (2010). What do retrospective subjective reports of childhood health capture? Evidence from the Wisconsin Longitudinal Study. *Research on Aging*, *32*(6), 698-714. <https://doi.org/10.1177/0164027510379347> (**Impact factor, 2010: 1.290)**

**Journal Articles Under Review (3)**

1.     **Bishop, N. J.**, Haas, S. A., & Quiñones, A. R. Cohort trends in chronic disease burden and multimorbidity among aging US adults. Under review at *The Journals of Gerontology, Series B: Social Sciences*, originally submitted September 15, 2021, revision submitted February 21, 2022.

2.     **Bishop, N. J.**, & Zhu, J. Racial/ethnic variation in the association between 4-year change in cystatin C and dietary quality in older Americans. Under review at *British Journal of Nutrition*, revision submitted November 15, 2021, revision submitted February 15, 2022.

3.     Flynn, T.\*, Goble, P., **Bishop, N.**, & Weimer, A. Early childhood hospitalization and problematic behaviors: A propensity score analysis. Under review at *Journal of Child Health Care*, submitted July 7, 2021, revise and resubmit due February 28, 2022.

**Journal Articles in Progress (1)**

1.     Zambrano, P.\*, Perez-Brena, N. J., Duncan, J., & **Bishop, N.** Coparenting dyads among Latinx adolescent parent families. To be submitted to *Journal of Family Psychology.*

**Non-refereed Articles (2)**

1.    Kronenfeld, J. J., Keith, V., **Bishop, N. J.**, & Ayers, S. (2010). Report of survey of sociologists with interests in mental health and medical sociology regarding health policy issues. *American Sociological Association Mental Health Section Newsletter*, *17*, 6-7.

2.     Kronenfeld, J. J., Keith, V., **Bishop, N. J.**, & Ayers, S. (2009). Report on survey of medical sociologists regarding health policy issues. *American Sociological Association Medical Sociology Newsletter*, *45*, 12-14.

**Reports (5)**

1.    **Bishop, N. J.**, Torres, C., & Gupta, S. (2014). *Arizona Health Status and Vital Statistics, 2013*. <https://pub.azdhs.gov/health-stats/report/ahs/ahs2013/index.php>

2.     **Bishop, N. J.**, & Hall, B. (2014). *Aging in Arizona: Health Status of Older Arizonans.* <https://pub.azdhs.gov/health-stats/report/aging/aia-report.pdf>

3.     **Bishop, N. J.**, Torres, C., & Gupta, S. (2014). *Differences in Health Status among Racial/Ethnic Groups, Arizona, 2011*. [https://pub.azdhs.gov/health-stats/report/dhsag/dhsag11/ethnic11.pdf](https://pub.azdhs.gov/health-stats/report/dhsag/dhsag11/ethnic11.pdf)

4.     **Bishop, N. J.**, Torres, C., & Gupta, S. (2014). *Health Status Profile of American Indians in Arizona, 2012 Data Book*. [https://pub.azdhs.gov/e-books/american-indians/az-american-](https://pub.azdhs.gov/e-books/american-indians/az-american-indians-2012/files/assets/common/downloads/HSAM%202012.pdf) [indians-2012/files/assets/common/downloads/HSAM%202012.pdf](https://pub.azdhs.gov/e-books/american-indians/az-american-indians-2012/files/assets/common/downloads/HSAM%202012.pdf)

5.     **Bishop, N. J.**, Torres, C., & Gupta, S. (2013). *Arizona Health Status and Vital Statistics, 2012*. <https://pub.azdhs.gov/health-stats/report/ahs/ahs2012/index.php>

**Papers Presented at Professional Meetings (10)**

1.     **Bishop, N. J.**, Haas, S. A., & Quiñones, A. R. (2021, November). *Birth cohort differences in multimorbidity burden among aging US adults*. Paper presented at the Gerontological Society of America's annual meeting, virtual.

2.     **Bishop, N. J.**, & Zhu, J. (2021, June). *Investigating Racial/Ethnic Disparities in the Association between AHEI 2010 and Change in Cystatin C in a Representative Sample of Older Americans*. Paper presented at the American Society of Nutrition virtual meeting, United States.

3.    Page, J. (Presenting)\*, Crixell, S. L., Markides, B. R.\*, **Bishop, N. J.**, & Biediger Friedman, L. M.(2017, April). *Comparison of Healthy Eating Index-2010 Scores of Preschool-Aged Children in a High-Risk Community to Those of an Age-Matched National Sample (NHANES 2009-2012)*. Paper presented at the Experimental Biology 2017 Conference.

4.     **Bishop, N. J.** (2011, March). *Examining Socioeconomic Variation in the Co-Evolution of Cognitive Decline and Functional Limitations among the Oldest Old*. Paper Presented at the Population Association of America's annual meeting.

5.     **Bishop, N. J.** (2010, April). *Exploring Disparities in the Cognitive Functioning of Older Americans Using Growth Curve Selection Modeling: Do Health Behaviors Play a Role?* Paper presented at the Population Association of America's annual meeting

6.     **Bishop, N. J.**, & Haas, S. A. (2009, April). *The Influence of Access: Longitudinal BMI Change and Socioeconomic Status in the Health and Retirement Study,1992-2006.* Paper presented at the Population Association of America's annual meeting.

7.     Haas, S. A., & **Bishop, N. J.** (2009, April). *What Do Retrospective Subjective Reports of Childhood Health Capture? Evidence from the WLS and the PSID*. Paper presented at the Population Association of America's annual meeting.

8.    **Bishop, N. J.** (2008, April). *Stretch to Fit: Yoga and the Contemporary Health Lifestyle*. Paper presented at the Pacific Sociological Association's annual meeting.

9.     **Bishop, N. J.** (2007, April) *Variations on Gender Modeling in the Televised Kitchen*. Paper presented at the Pacific Sociological Association's annual meeting.

10.     **Bishop, N. J.** (2005, April), *Kick It up a Notch: Masculinity, Hierarchy and the Televised Kitchen*. Paper presented at the Pacific Sociological Association's annual meeting.

**Posters Presented at Professional Meetings (15)**

1.     Tucker, J.\*, **Bishop, N. J.**, Wang, K. & Phillips, F.(2021, November). *Quality of Social Relationships Moderates the Impact of Marital Transitions on Depression for Older Adult Women.* Poster presented at the Gerontological Society of America's annual meeting, virtual*.*

2.     **Bishop, N. J.**, Ullevig, S., Wang, K., Zuniga, K., & Tucker, J.\* (2020, November). *Dietary Quality Predicts Short Term Change in Mobility Limitations in Older US Adults.* Poster presented at the Gerontological Society of America's annual meeting, virtual.

3.     Tucker, J.\*, & **Bishop, N. J.** (2020, November). *Social Support and Depressive Outcomes in Bereaved Older Adults: An Analysis of the Health and Retirement Study.* Poster presented at the Gerontological Society of America's annual meeting, virtual.

4.     **Bishop, N. J.** (2020, June). *Estimating Sample Size Required to Establish an Association between Walnut Intake and Cognitive Change in Older Adults: An Application of Monte Carlo Power Analysis*. Poster presented at the American Society of Nutrition virtual meeting, United States.

5.     **Bishop, N. J.**, & Zuniga, K. E. (2019, November). *Investigating Walnut Consumption and Cognitive Health in a Representative Sample of Older US Adults*. Poster presented at the Gerontological Society of America's annual meeting, Austin, TX, United States.

6.     **Bishop, N. J.**, & Wang, K. (2019, November). *Parallel Development of Memory, Disability, and Comorbidity in US Adults Age 65 and Older.* Poster presented at the Gerontological Society of America's annual meeting, Austin, TX, United States.

7.    **Bishop, N. J.**, Zuniga, K. E., & Noon, B.\* (2019, June). *Egg Consumption, Multi-Domain Cognitive Performance, and Short-Term Cognitive Change in a Representative Sample of Older U.S. Adults*. Poster presented at the American Society of Nutrition, Baltimore, MD, United States.

8.     Turner, A.\*, Zuniga, K., & **Bishop, N. J.** (2019, June). *Relationship between Dietary Lutein and Cognition in an Older Adult Population*. Poster presented at the American Society of Nutrition, Baltimore, MD, United States.

9.     **Bishop, N. J.**, Zuniga, K. E., & Noon, B.\* (2019, April). *Caloric Intake and Dietary Factors are Associated with Onset of Physical Disability and Mortality in a Representative Sample of Older Adults*. Poster presented at the Population Association of America's annual meeting, Austin, TX, United States.

10.     **Bishop, N. J.**, & Wang, K. (2018, April). *Food Insecurity, Chronic Disease Burden, and Mobility Limitations among Older U.S. Adults: Findings from the Health and Retirement Study and Health Care and Nutrition Study" Population Association of America*. Poster presented at the Population Association of America's annual meeting.

11.     **Bishop, N. J.**, & Wang, K. (2018, April). *Food Insecurity, Chronic Disease Burden, and Mobility Limitations among Older U.S. Adults: Findings from the Health and Retirement Study and Health Care and Nutrition Study" Population Association of America*. Poster presented at the Population Association of America's annual meeting.

12.     **Bishop, N. J.**, & Zuniga, K. E. (2017, November). *Empirically Derived Dietary Patterns and Cognitive Decline in Older Adults: An Application of Exploratory Factor Mixture Models*. Poster presented at the American Public Health Association's annual meeting, Atlanta, GA

13.     Thornton, H., Biediger-Friedman, L. M., **Bishop, N. J.**, Abohosh, A.\*, Alhado, M.\*, Moyer, T.\*, Powers, R.\*, Royer, H.\*, & Silva, M.\* (2017, March). *Pilot Study to Assess Food Security at a Large University in Central Texas*. Poster presented at the Texas Association of Nutrition and Dietetics' annual meeting.

14.     **Bishop, N. J.**, & Zuniga, K. E. (2016, November). *Identifying Diet Typologies and Predictors of Macronutrient Consumption among Aging Americans*. Poster presented at the Gerontological Society of America's annual meeting, New Orleans, LA.

15.    Zuniga, K. E., & **Bishop, N. J.** (2016, March). *Cancer Treatment and Cognitive Decline in the Health and Retirement Study*. Poster presented at the International Cancer and Cognition Task Force Conference, Netherlands.

**Posters Presented at University Symposium (6)**

1.     **Bishop, N. J.**, Ullevig, S., Wang, K., Zuniga, K., & Tucker, J.\* (2021, April). *Dietary Quality Predicts Short Term Change in Mobility Limitations in Older US Adults.* Poster presented at the Health Scholar Showcase, Texas State University.

2.    **Bishop, N. J.**, Zuniga, K. E., & Noon, B.\* (2019, April). *Caloric Intake and Dietary Factors are Associated with Onset of Physical Disability and Mortality in a Representative Sample of Older Adults*. Poster presented at the Health Scholar Showcase, Texas State University.

3.     **Bishop, N. J.**, & Wang, K. (2018, February). *Food Insecurity, Chronic Disease Burden, and Mobility Limitations among Older U.S. Adults: Findings from the Health and Retirement Study and Health Care and Nutrition Study.* Paper presented at the Health Scholar Showcase, Texas State University.

4.     **Bishop, N. J.**, & Zuniga, K. E. (2017, November). *Empirically-Derived Dietary Patterns and Cognitive Decline in Older Adults: An Application of Factor Mixture Models.* Paper presented at the FCS Food Day Research Symposium, Texas State University, School of Family and Consumer Sciences.

5.     Biediger-Friedman, L., Thornton, H., **Bishop, N. J.**, Crowder, L.\*, & Varnell, K.\* (2017, November). *There's Nothing to Eat:" Food Security at Texas State University*. Paper presented at the FCS Food Day Research Symposium, Texas State University, School of Family and Consumer Sciences.

6.     **Bishop, N. J.**, & Zuniga, K. E. (2017, February). *Identifying Diet Typologies
and Predictors of Macronutrient Consumption among Aging Americans*. Paper presented at the Health Scholar Showcase Texas State University.

**Roundtables (1)**

1.     **Bishop, N. J.**, & Schaefer, D. R. (2009, August). American Sociological Association, annual meeting, "The Academic Influence of the Adolescent Peer Group: How Does Variation in Social Network Capital Influence Individual Outcomes?"

**Invited Talks, Lectures, and Presentations (4)**

1.     **Bishop, N. J.**, & Zuniga, K. (2019, July). "Walnut Consumption and Cognitive Trajectories in a Representative Sample of Older U.S. Adults". California Walnut Commission Health Research Conference.

2.     **Bishop, N. J.**, Tummala, P., & Herrington, D. (2013, August). "2013 Arizona State Health Assessment," University of Arizona Mel & Enid Zuckerman College of Public Health.

3.     **Bishop, N. J.** (2012, June). "Understanding the Arizona Department of Education's 2012 A-F Letter Grade School Accountability System."

4.     **Bishop, N. J.** (2011, October). Making Connections, Oklahoma Department of Mental Health and Substance Abuse Services, annual conference, "Comparison of National DUI Data (and more!)."

**Presented Workshops (2)**

1.     **Bishop, N. J.** (2021, March). Department of Family and Consumer Sciences/College of Applied Arts faculty workshop, "An Introduction to R and R Studio Cloud" Texas State University.

2.     **Bishop, N. J.** (2015, October). Department of Family and Consumer Sciences faculty workshop, "For Good (Latent) Measure: Guidelines in Scale Development" Texas State University.
